spring:
  config:
    datasource:
      url: "jdbc:mysql://somewhere-dev-host:3306/myapp_db"
      username: "username"
      password: "password"
    jpa:
      hibernate:
        ddl-auto: update
      generate-ddl: true
      show-sql: true